[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting = "FGjJWvjxTevMxUaBK4pXGvYr8VupeUUXB2K35ht9BB29"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
